sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
  minio:
    endpoint: http://localhost:9000  # 9000 for API, 9001 for browser
    bucketName: sky-image
    accessKey: lg3tda2hqqL2nftmn9CR
    secretKey: 5JC8VPn8OMOwqkQG2ubC4GLFFQlvFK8HLlSKjSqX
  redis:
   host: localhost
   port: 6379
   password: 1
#   database: 0  # DB0，redis 默认会有 16 个互相隔离的数据库